### ISSUE TITLE
voiceflow-pro-ui: ~86 pre-existing TypeScript errors — project does not compile (blocks ui-e2e build)

### ISSUE THREAD

**Issue by kimhons** [kimhons/VoiceFlow-PRO#9]
## Summary

`voiceflow-pro-ui` has **~86 TypeScript errors** and does not compile. This was masked for a long time because the `ui-e2e` CI always failed earlier at `pnpm install` (the `node:sqlite` bug, fixed in #8). With install fixed, CI now reaches `pnpm run build` and fails there. The project has effectively **never compiled**.

Reproduce (from `voiceflow-pro-ui/`, Node 22):
```bash
corepack enable && pnpm install --no-frozen-lockfile
pnpm run build   # tsc -b && vite build  -> ~86 TS errors
```

## Error breakdown (86 errors across 13 files)

| TS code | Count | Meaning |
|---|---|---|
| TS2339 | 26 | Property does not exist on type |
| TS2322 | 25 | Type not assignable |
| TS2307 | 9 | Cannot find module |
| TS2724 | 5 | No exported member (did you mean …) |
| TS2686 | 4 | `React` refers to a UMD global (missing `import React`) |
| TS2367 | 3 | Comparison has no overlap |
| TS2304 | 3 | Cannot find name |
| TS2451 | 2 | Cannot redeclare block-scoped variable |
| TS2305 / TS2300 | 4 | No exported member / duplicate identifier |

## Notable, concrete problems

- **`src/App.tsx` imports a lazy-loading API that doesn't exist** in `./components`: `LazyComponent`, `useComponentPreloader`, `LazyVoiceRecording`, `LazyTranscriptionDisplay`, `LazyLanguageSelector`, `LazyAudioVisualization`, `LazySettingsPanel` (TS2305/TS2724). Either these components were never implemented or were removed.
- **`src/App.tsx` declares `handleRecordingStateChange` twice** (TS2451) — a duplicate function, so the file as written is contradictory.
- **Design-token type mismatches** in `App.tsx`: `spacing.base/lg/xl`, `typography` used as if structured but typed as `string`; a `FontWeight` assigned `() => string` (TS2339/TS2322). Suggests the theme/token types and their usage drifted apart.
- **`src/utils/accessibility.ts` contains JSX** but has a `.ts` extension (should be `.tsx`); once renamed it also needs `import React`.
- **`src/utils/platform.ts`**: comparisons between `PlatformType` and `"web"` that "have no overlap" (TS2367) — the `PlatformType` union likely doesn't include `"web"`.
- **`vite.config.ts`**: `.split('/').pop()` used without a null-guard (TS2532); invalid `server.compress` option (TS2769).

## Recommended approach

This is real development work, not a config fix — the code references APIs that don't exist and has contradictory declarations. Suggested order:
1. Reconcile `./components` exports vs `App.tsx`'s imports (implement or remove the lazy-loading layer; fix the duplicate `handleRecordingStateChange`).
2. Fix the theme/token types so `spacing`/`typography`/`FontWeight` usage type-checks.
3. Rename `accessibility.ts` → `.tsx` and add `import React`.
4. Fix `PlatformType` to include `"web"` (or fix the comparisons) and the two `vite.config.ts` issues.
5. Re-run `pnpm run build` to zero, then the `e2e/smoke.spec.ts` Playwright test can actually run.

## Context
- Unblocked by #8 (node:sqlite install fix). Until this is fixed, the `ui-e2e` workflow will remain red at the `build` step.
- Do NOT weaken/skip to force green — the errors reflect genuinely broken code that should be made correct.
